### ISSUE TITLE
Limit of 2 connections

### ISSUE THREAD

**Issue by dermicha** [YunoHost-Apps/jitsi_ynh#29] opened 2020-03-13 07:11 UTC
Hey,

I have a fresh updated yunohost. A few days ago I have added Jitsi Meet. With up to two participants it works great. But all further participants are getting a user/password dialog. Of course I have noch setup a password. My Meet instance should be open for all, no user limitations. 

These files could not be loaded (Error 404):
/ynh_overlay.css
/custom_overlay.css
/custom_overlay.css
/custom_portal.js

I see no further errors. 

Whats going wrong? 

Thanks for your help. 

Cheers, derMicha

**Comment by AkselRocks** [comment] 2020-03-13 07:16
Unfortunally jitsi for yunohost has limitations (new added yesterday in description):
- Can only be used using Chrome/Chromium
- Is limited to two participants

see [here](https://github.com/YunoHost-Apps/jitsi_ynh#important-points-before-installing)

**Comment by dermicha** [comment] 2020-03-13 07:51
<img width="555" alt="Screenshot 2020-03-13 at 08 51 12" src="https://user-images.githubusercontent.com/1823956/76600763-d8851c00-6507-11ea-9a43-08de51678d88.png">

**Comment by dermicha** [comment] 2020-03-13 07:54
Why that limitation to two participants? 

That's worthless.

**Comment by AkselRocks** [comment] 2020-03-13 07:58
Maybe @yalh76 can answer your question.

I also find it a great pity, that yunohost can't support the full spectrum of jitisi possibilities ...

**Comment by supermamie** [comment] 2020-03-13 13:10
Is there an alternative available in YunoHost able to handle 19-20 users ?

**Comment by dermicha** [comment] 2020-03-13 14:16
I have setup my own unlimited instance based on a 5Eur virtual machine in about 15 Min.

https://fatiherikci.com/en/install-jitsi-meet-on-debian-10/

after that:
cd /usr/share/jitsi-meet/scripts
./install-letsencrypt-cert.sh

Done! Works fine!!

**Comment by supermamie** [comment] 2020-03-13 14:20
I don't want to mess in my  NextCloud instance, and it is only Debian 9 :disappointed:

**Comment by supermamie** [comment] 2020-03-13 16:14
I just took a 6€ server to try for a  few week :)

**Comment by AkselRocks** [comment] 2020-03-13 16:47
Does this also work for firefox (and other browsers)?

**Comment by dermicha** [comment] 2020-03-13 23:21
@AkselRocks Chrome/Chromeium, Brave (after granting auto play), Firefox

**Comment by yalh76** [comment] 2020-03-14 02:33
> 
> 
> Why that limitation to two participants?
> 
> That's worthless.

Because I wasn't able to make it works, but if someone can improve it, PR are open ;)

**Comment by yalh76** [comment] 2020-03-14 02:35
> 
> 
> Is there an alternative available in YunoHost able to handle 10-20 users ?

It's not a YunoHost a limitation but this package limitation

**Comment by AkselRocks** [comment] 2020-03-14 06:26
> > Is there an alternative available in YunoHost able to handle 10-20 users ?
> 
> It's not a YunoHost a limitation but this package limitation

so when yunohost supports debian 10 it will work?

**Comment by yalh76** [comment] 2020-03-14 14:00
> 
> 
> > > Is there an alternative available in YunoHost able to handle 10-20 users ?
> > 
> > 
> > It's not a YunoHost a limitation but this package limitation
> 
> so when yunohost supports debian 10 it will/should work?

I don't know because I don't know what is the issue....

**Comment by edddii** [comment] 2020-03-19 21:59
I've found this somewhere... but I'm too inexperienced to test it.

>Jitsi Videobridge can run behind a NAT, provided that both required ports are routed (forwarded) to the machine that it runs on. By default these ports are TCP/4443 and UDP/10000.
If you do not route these two ports, Jitsi Meet will only work with video for two people, breaking upon 3 or more people trying to show video.

**Comment by MemoryComparison** [comment] 2020-03-20 14:00
I just tried on a server that has no NAT, and the chat crashed as soon as the third person joined. Is there a way to access logs?

**Comment by yalh76** [comment] 2020-03-20 15:46
> 
> 
> I've found this somewhere... but I'm too inexperienced to test it.
> 
> > Jitsi Videobridge can run behind a NAT, provided that both required ports are routed (forwarded) to the machine that it runs on. By default these ports are TCP/4443 and UDP/10000.
> > If you do not route these two ports, Jitsi Meet will only work with video for two people, breaking upon 3 or more people trying to show video.

Yes it's written in the readme.. But even with that I wasn't abble to make it work for more than 2 users.

**Comment by yalh76** [comment] 2020-03-20 15:47
> 
> 
> I just tried on a server that has no NAT, and the chat crashed as soon as the third person joined. Is there a way to access logs?

yes doing `journalctl -feu jitsi-jicofo` `journalctl -feu jitsi-videobridge` `journalctl -feu metronome`

**Comment by MemoryComparison** [comment] 2020-03-20 19:34
Thanks @yalh76 for the info.

The only strange thing I can find is that when the third user came in, it seems that an IQ does not get a response. I can see the Processing IQ line but not the responding to IQ one.

The processing line is this:
FINE: [108] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Processing IQ (packetId 74sjS-4972): <iq id="74sjS-4972" type="result" to="jitsi-videobridge.jitsi.example.com" from="jitsi.example.com"/>

**Comment by alexAubin** [comment] 2020-03-23 19:24
Dunno if that helps, but ljf points me to this topic on chatons.org that may give some pointers : https://forum.chatons.org/t/jitsi-meet-petite-aide-de-configuration/912

Not sure to understand everything since I'm not really familiar with Jitsi, but somebody mentions a turn/coturn server which seems related to this.

(Another possible test, if not already done, and to validate wether or not it's a NAT/firewall issue, would be to test an instance on a VPS with yunohost-firewall stopped - so supposedly not inside a NAT, with full port exposition)

**Comment by yalh76** [comment] 2020-03-24 20:13
Thanks @alexAubin I will try to implement a coturn server

(I don't have a vps but I'm preaty OK with NAT and firewall stuff)

PS: as reminder/information for all:
- I don't know how jitsi works and don't plan to use it
- I rewrited this [abandonned ](https://github.com/YunoHost-Apps/jitsi_ynh/commits/master?after=ac4e461926126caa6961b34e1674e475451ecedc+69) package from scratch using the [detailed manual installation instructions](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md) because a lot of people wanted to use it
- I adapted it to work with xmpp server metronome included with YunoHost (instead of xmpp server prosody is made for)
- I'm like a one year old linux user but trying to contribute [as I can](https://dash.yunohost.org/app_maintainer_dash/yalh76)
- any PR / help is more than welcome

**Comment by supermamie** [comment] 2020-03-25 08:13
Just if it can help, the Synapse app installs a coturn server too.
I never tested it with more than 2 users because it only work from inside my home network (I think my FAI box is the problem).

**Comment by MemoryComparison** [comment] 2020-03-28 10:29
> (Another possible test, if not already done, and to validate wether or not it's a NAT/firewall issue, would be to test an instance on a VPS with yunohost-firewall stopped - so supposedly not inside a NAT, with full port exposition)

I just tried that. The problem persists.

**Comment by yalh76** [comment] 2020-04-07 00:42
If someone could test jitsi from the coturn branch doing `yunohost app install https://github.com/YunoHost-Apps/jitsi_ynh/tree/coturn`. It should install well but I'm really not sure of Jitsi or coturn implementation.

**Comment by curious-jeremy** [comment] 2020-04-09 17:33
Hi @yalh76 
Thank you for trying to make it work!

I tested the `coturn` branch, and unfortunately from what I can see, it doesn't work better than the `master` branch. I didn't dig too much yet, but from my tests, I couldn't see any real different behavior between the two branches.

**Comment by yalh76** [comment] 2020-04-09 17:47
thanks for the informations, It's what I 've seen. @Tagadda plan to do other tests. We will see.

**Comment by plslvval** [comment] 2020-04-11 12:28
i hit same problem and i think we should have a way to drive tests to find out what is the bottleneck here. I can help, i think we have to find a chat channel to do our investigation altogether from different places and the narrow this issue, i propose this pad : https://serveur.slv-valbonne.fr/pad/p/JitsiYunohostMultiPeerInvestigation

**Comment by yalh76** [comment] 2020-04-13 15:49
In #43 I've completly reworked the installation process to use .deb files and to be closest of a jitsi-meet installation aka https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md.
In this branch, no need to create all the sub-domains. If you created them, you should remove them doing `yunohost domain remove ....` for each domains.

I also disable p2p: https://github.com/YunoHost-Apps/jitsi_ynh/blob/51f7263ecc5c614702a03d53b3367df6990bb932/conf/config.js#L331-L338 to be sure even using chromium it will use jitsi-videobrige

For now, still doesn't work, seems something around jitsi-videobridge authentication on metronome. Can't find how to solve that.

**Comment by MensoifG** [comment] 2020-06-17 20:03
I just encountered such problem during installation
2020-06-17 19:36:16,041: WARNING - https://download.jitsi.org/jitsi-videobridge/linux/jitsi-videobridge-linux-x64-1130.zip:
2020-06-17 19:36:16,042: DEBUG - 2020-06-17 19:36:16 ERROR 404: Not Found.'
2020-06-17 19:36:16,042: WARNING - 2020-06-17 19:36:16 ERROR 404: Not Found.

**Comment by yalh76** [comment] 2020-06-24 21:46
duplicate of #10

**Closed by yalh76** 2020-06-24 21:46 UTC
Labels: bug, duplicate
