### ISSUE TITLE
Loop error

### ISSUE THREAD

**Issue by bjarkan** [YunoHost-Apps/jitsi_ynh#16] opened 2020-01-14 00:18 UTC
I've done EVERYTHING, the domains, the let's encrypt certificates, ports in the router... everything. Even tried the testing branch....

It show a message that it has been disconnected, wait some seconds and reconnect... and back again, is like i forgot anything. But everything else works, it ask for camera permits, audio, blah blah, but suddenly it disconnect
![Captura de pantalla_2020-01-14_01-18-02](https://user-images.githubusercontent.com/6814404/72302895-c142c300-366b-11ea-993c-f20801878174.png)
...

**Comment by yalh76** [comment] 2020-01-15 19:24
You have to check is all jitsi services are up and running.

1. jitsi-jicofo
2. jitsi-videobridge


You can also check the logs of those services doing:

1. `journalctl -feu jitsi-jicofo`
2. `journalctl -feu jitsi-videobridge`

To see if there are some errors

**Comment by bjarkan** [comment] 2020-01-16 19:46
in jicofo found just "wrong" this....

ene 16 20:35:06 miradordemontepinar.net jicofo.sh[555]: Jicofo 2020-01-16 20:35:06.744 ADVERTENCIA: [220] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.processJingleIQ().368 unsupported action session-terminate

and this
ene 16 20:35:05 miradordemontepinar.net jicofo.sh[555]: Jicofo 2020-01-16 20:35:05.702 GRAVE: [50] org.jitsi.jicofo.AbstractChannelAllocator.log() Failed to allocate channels using bridge: jitsi-videobridge.jitsi.miradordemontepinar.net

ene 16 20:35:05 miradordemontepinar.net jicofo.sh[555]: Jicofo 2020-01-16 20:35:05.703 GRAVE: [50] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() One of our bridges failed: jitsi-videobridge.jitsi.miradordemontepinar.net

by the way... I added the lastest https://modules.prosody.im/mod_turncredentials.html into my metronome and configure 
turncredentials_secret = "************";
turncredentials_host = "miradordemontepinar.net";

into metronome.lua.cfg... adding the module to load too...

I finally achieve multiple clients connected... but no video nor audio... I will continue my  investigation...

**Comment by bjarkan** [comment] 2020-01-16 20:08
I found a lot of problems... no audio nor video... a this wonderfull message
![Captura de pantalla_2020-01-16_21-06-40](https://user-images.githubusercontent.com/6814404/72559046-3b5d8c80-38a4-11ea-95bb-29f1bde9aa3d.png)]

I'll insist...

**Comment by bjarkan** [comment] 2020-01-16 20:36
Impossible... i'm about to give up...

**Comment by yalh76** [comment] 2020-01-17 00:16
Well, Jitsi for Yunohost is difficult. 
Jitsi is made for xmpp server prosody.
Yunohost already provide an xmpp server: Metronome, a fork from prosody.
So installation is fully manual... That can explain that Jitsi is difficult to package for Yunohost

Maybe you can try to remove it and install a newer version doing `yunohost app install https://github.com/YunoHost-Apps/jitsi_ynh/tree/1.0.3729`

**Comment by bjarkan** [comment] 2020-01-17 21:27
I tried that too, and metronome is acting up now... I give up... maybe the solution is to use the docker version that includes all the packages in a "box" or install in a different machine, but i'm sorry, i'm a bit sick and tired of it... 

Maybe I'll try to install the docker version, and if i achieve it i'll try to send you a message with an reproductible step by step guide, I do think it will be easier to package it, since in fact is already a pack, with internal prosody included but not exposed, so will not create conflicts with metronome, and several other issues we are addressing...

have a nice day (i close the bug, but if i'm successful you'll hear from me...)

**Comment by bjarkan** [comment] 2020-01-17 22:36
https://community.jitsi.org/t/yunohost-install-jitsi-as-docker-or-just-debs/21472

asking for help to the jitsi community...

**Comment by bjarkan** [comment] 2020-01-20 12:14
@yalh76  i found a way to make it work... i include here a link to the virtual machine (you can import it in virtualbox) and the files for the yunohost instance, nginx conf and host file... with this... it works...

the root user have for password "00rtb2l2" you can try... everything is configured and tested... not the best solution, but includes /etc/prosody changes to add turn server /etc/jitsi/videobridge/sip-comunicator changes to allow more than 2 user... blah blah blah... test it as you want it... it works.

As you import the machine, don't forget to change the domain... right now the domain is jitsi.miradordemontepinar.net (it's a clone of my server, that you can try if you want to)

https://miradordemontepinar.net/nextcloud/index.php/s/tktk8snSS8T4CGA

**Comment by yalh76** [comment] 2020-01-21 19:29
Thanks a lot, I will check that :)

**Comment by yalh76** [comment] 2020-01-21 21:45
OK I've checked, as far as I've understood, the ova is a debian without YunoHost and with jitsi installed from .deb 

The point is:
- Jitsi is packaged with Prosody
- Yunohost provide Metronome
- Metronome and Prosody can't be installed on the same server.

**Comment by bjarkan** [comment] 2020-01-21 22:08
True... is a "workaround" of the problem, isolate the problem in a virtualbox machine... but the configuration files for nginx and the configuration of jitsi, could help you... The file sipcomunicator.properties (/etc/jitsi/videobridge)file is very important to redirect the traffic to 4443 instead of 443 that will collide with the web server... It is not a docker but is the next best thing.

In my opinion is the fastest way to have jitsi installed and working, pack it in a vm or pack it in docker.

I explore the first approach, i need to do some testing, to know it better... but the next natural step is to go to a docker container, that in this case will be easily deploy in yunohost... since the docker version only expose 2 ports... 4443 tcp, and 10000 udp, the prosody included with the docker version is inside the docker and only used for internal signaling, not anything else.

After having this experience, I do believe that to deploy in yunohost we have two alternatives, drop metronome or go docker/vm solution. Since the first one is not going to happen, we have 2 choices, or do it with docker or do it with virtualbox.

**Comment by AkselRocks** [comment] 2020-01-22 07:36
That seems to be an good idea to me!
yunohost installing a docker container containing the jitsi app.

This way can also be used for other apps, which cannot be updated, because yunohost does not (yet) support the latest debian version.

**Comment by bjarkan** [comment] 2020-01-22 10:37
Nextcloud even have a docker version, so we can surpass the debian 9 limitations, with an alternative packaging using docker. Nextcloud right now is v18, and we still use v15... maybe use docker is a solution to update apps and surpass limitations and package faster...

**Comment by AkselRocks** [comment] 2020-01-22 11:24
Same/similar with Hubzilla. 
Latest version is 4.6 (with php 7.3), yunohost uses 4.0 (with debian 9 default php 7.0).
And there is a up-tp-date docker version.

**Comment by yalh76** [comment] 2020-01-23 01:01
Well well well... YunoHost aims to democratize self-hosting and to be installed on many kinds of hardware. Even on Olimex card and I'm not sure that docker can work properly on that kind of hardware. You will find more discussion about docker on [Yunohost forum]( https://forum.yunohost.org/t/advantages-of-classic-install-over-docker/4377)

From my part, as a linux beginner, I'm more into doing without docker but feel free to create some new packages using docker, there are already some.

**Comment by bjarkan** [comment] 2020-01-24 08:55
@yalh76 I'm no expert, but i'll try to create a nextcloud install pack based in docker and jitsi too... I will start with the second, if i'm successful will go with nextcloud. Both are solutions based in interpreted languages (jitsi is javascript and java, on the other hand nexcloud is php) so compatibility with other hardware is not sure, but highly possible... I'm gonna try, try do not hurt, i tried vm and solve the problem, so the next best thing is docker... or snap... I will fork this "official" yunohost jitsi support to jitsi_docker_ynh... i will try, if it's help full for just one single person, i'm happy.

Nextcloud is almost abandon in yunohost 'cos php and debian 9, if dockerize it could help have the latest version... is an advance.

I'll try my best, sadly the amount of time i can dedicate to this matter is too small, but I will try my best

**Comment by Neustradamus** [comment] 2020-03-28 01:56
Any news?

**Comment by yalh76** [comment] 2020-03-29 03:22
> 
> 
> Any news?

Any help ?

**Comment by rosbeef** [comment] 2020-06-15 14:57
Hi!, i had a problem like that on my odroid hc1 . this one hay 2 gb of ram.
> journalctl | grep jicofo
returns
`Jun 15 00:27:01 domain.tld jicofo.sh[9671]: Error occurred during initialization of VM
Jun 15 00:27:01 domain.tld jicofo.sh[9671]: Could not reserve enough space for 3145728KB object heap
`i read https://jitsi.org/jitsi-videobridge-performance-evaluation/
So i decided to reduce the space reservation to 500meg for the javavm in both of jitsivideobridge and jicofo start script. knowing that i will never do 100 participant confcall.

> /var/www/jitsi/jitsi-jicofo/jicofo.sh
`LD_LIBRARY_PATH=$libs exec java -Xmx**572m** -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=$libs $LOGGING_CONFIG_PARAM $JAVA_SYS_PROPS -cp $cp $mainClass $@`

> /var/www/jitsi/jitsi-videobridge/jvb.sh 
`if [ -z "$VIDEOBRIDGE_MAX_MEMORY" ]; then VIDEOBRIDGE_MAX_MEMORY=**572m**; fi

LD_LIBRARY_PATH=$libs exec java -Xmx$VIDEOBRIDGE_MAX_MEMORY $VIDEOBRIDGE_DEBUG_OPTIONS -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=$libs $LOGGING_CONFIG_PARAM $JAVA_SYS_PROPS -cp $cp $mainClass $@`

tell me if that helps you

**Comment by yalh76** [comment] 2020-06-24 21:47
duplicate of #10

**Closed by yalh76** 2020-06-24 21:47 UTC
Labels: bug, duplicate
